### PR TITLE
Make $valid_through_dt available as a pass-by-reference parameter

### LINKED ISSUE #13: Method to extract valid through date from csig
For https://www.drupal.org/project/drupalorg/issues/3061248, I'd like to keep track of the expiration date of generated csigs, so those artifacts can be purged and regenerated before they expire.

Since the signing oracle will be separate from what calls it, and the caller is already invoking `Verifier::verifyCsigMessage()` to validate the signing, I think it makes sense to have a `Verifier` method able to return the date.

Could `Verifier::verifyCsigMessage()` return an array of `['message' => …, 'valid_through_dt' => …]` or does another method make sense?

### PR DESCRIPTION
**Pull request by drumm**
Fixes #13 

As suggested by @pwolanin, use a pass-by-reference parameter that gets set to the valid-through date.

### CODE REVIEW

**Comment by davidstrauss** [comment]
Can I get the context of the suggestion (like a link)? The motivation for this change is slipping my mind.

**Comment by pwolanin** [comment]
On slack drumm said the idea was to be able to run this as QA of of file generated by the signing oracle and also get back the date so that the expire date of each file could be externally tracked.

**Comment by pwolanin** [comment]
I suggested the pass-by-ref instead of changing the return value to array or object including the valid data and message since this is a little outside the main use case of juts validating the message.

**Comment by drumm** [comment]
This is currently at https://git.drupalcode.org/project/drupalorg/blob/8741b418585d40af1b393cadfe98cd8a90e27810/drupalorg/drupalorg.drush.inc#L434. The code in the function above that is temporarily doing all the signing with test keys, until we have the proper signing oracle and process set up. This started out verifying that I got the implementation right. It will be good to keep, to verify the signing oracle implementation, and catch any future problems with the signing oracle.

Knowing the valid-through date will be needed for managing signed artifacts, we can regenerate or remove them as the date approaches. Getting the date from the artifact itself will be more reliable than some other coordination.

**Comment by drumm** [comment]
https://git.drupalcode.org/project/drupalorg/blob/51bdce796641c7d5725b72b69d92ee4875eec96c/drupalorg/drupalorg.drush.inc#L434 is now a better example of where I’m calling `Verifier::verifyCsigMessage()`. It is now checking that the signed message data matches what was passed in. This is where I’ll be using the valid-through date, too.

**Pull request merged**
