### PR TITLE
Add fixtures for a multi-file check

### PR DESCRIPTION
**Pull request by davidstrauss**
I've tested validation of this set using the CLI instructions in the README. Here's the result:

    [straussd@toolbox multiple-files]$ tail --lines=+6 module.csig | signify -C -p intermediate.pub -x -
    Signature Verified
    a.txt: OK
    c.txt: OK
    d.txt: FAIL
    b.txt: FAIL

This result is probably unsurprising given the file content. If we want to use this fixture for a fully passing test of the file set, we can copy it to another directory and restore `b.txt` and `d.txt` to their eponymous content.

### CODE REVIEW

**Comment by davidstrauss** [comment]
Here's the process I used for creating the fixtures (with a few editorial cleanups):

https://gist.github.com/davidstrauss/227ab140d90c60962a23449351a2bd81

**Comment by heddn** [comment]
@davidstrauss `intermediate.pub` isn't in this PR. I can't run the verification.

**Comment by heddn** [comment]
I figured it out. root.pub is the intermediate key.

**Comment by davidstrauss** [comment]
> root.pub is the intermediate key

This is not actually the case. (It is really the root public key.) The intermediate key is bundled with the CSIG, much as it happens in TLS for intermediate certificates. This way, the necessary intermediate key (and the signature on it by the root key) flows with the signatures done by the intermediate key.

**Comment by heddn** [comment]
It would be nice to have a test case that runs over it. Perhaps that uses the new `FailedCheckumFilter` to validate things?

**Comment by davidstrauss** [comment]
> It would be nice to have a test case that runs over it. Perhaps that uses the new FailedCheckumFilter to validate things?

That would be great!

**Pull request merged**
